CREATE TABLE ACCOUNT(
	ID INT primary KEY,
    NAME VARCHAR(250) UNIQUE,
    BALANCE INT NOT NULL DEFAULT 0
	);

SELECT * FROM ACCOUNT;
    
-- ADD NEW COLUMN
ALTER TABLE ACCOUNT ADD INTEREST FLOAT NOT NULL DEFAULT 0;

-- MODIFY COLUMN DATA TYPES
ALTER TABLE ACCOUNT MODIFY INTEREST DOUBLE NOT NULL DEFAULT 0;

DESC ACCOUNT;			-- DESCRIBE ACCOUNT

-- CHANGE COLUMN / RENAME COLUMN
ALTER TABLE ACCOUNT CHANGE COLUMN INTEREST SAVING_INTEREST FLOAT;

-- DROP / DELETE COLUMN
ALTER TABLE ACCOUNT DROP SAVING_INTEREST

-- RENAME TABLE NAME
ALTER TABLE ACCOUNT RENAME TO ACCOUNT_DETAILS;

SELECT * FROM ACCOUNT_DETAILS;