CREATE DATABASE CUSTOMER;

USE CUSTOMER;

CREATE TABLE CUSTOMER(
	ID INTEGER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(25),
    ADDRESS VARCHAR(225),
    GENDER CHAR(1),
    CITY VARCHAR(225),
    PINCODE INTEGER(6)
    );

INSERT INTO CUSTOMER
	(ID, CUSTOMER_NAME, ADDRESS, GENDER, CITY, PINCODE) VALUES 	
		(125,'Manas Kumar Pradhan', 'Baunsadiha', 'M', 'BHOGRAI', 756035),
        (126,'Rajesh Pradhan', 'Baunsadiha', 'M', 'BHOGRAI', 756035),
        (127,'Subas Mohanty', 'Bagda', 'M', 'BHOGRAI', 756035),
        (128,'Aswini Kumar Panigrahi', 'Badapokhari', 'M', 'SORO', 756047),
        (129,'Jyotiranjan Mohanty', 'Jaleswar', 'M', 'JALESWAR', 756075),
        (130,'Satyajit Sahu', 'Balasore', 'M', 'BALASORE', 756001);
        
     

INSERT INTO CUSTOMER VALUES (
	131,'Pabitra Panigrahi', 'Badapokhari', 'M', 'SORO', 756047);

SELECT * FROM CUSTOMER;

-- REPLACE
REPLACE INTO CUSTOMER (ID, ADDRESS) VALUES
	(130, 'Motiganj');				-- REPLACE THE CORRESPONDING VALUE AND OTHER IS NULL

REPLACE INTO CUSTOMER (ID, ADDRESS) VALUES
	(132, 'Motiganj');				-- TREATED AS INSERT AS NOT EXITS
    
REPLACE INTO CUSTOMER SET ID = 131,   CUSTOMER_NAME = 'OK';			-- ANOTHER ARE NULL 

REPLACE INTO CUSTOMER(ID, CUSTOMER_NAME,PINCODE)
	SELECT ID,CUSTOMER_NAME,PINCODE
    FROM CUSTOMER WHERE ID = 129;
    
    
-- UPDATE
UPDATE CUSTOMER SET ADDRESS = 'Mumbai', Gender = 'F' WHERE ID = 129;

-- UPDATE MULTIPLE ROWS
SET SQL_SAFE_UPDATES =1;			-- 0 REFERS FOR UNSAFE MODE AND 1 FOR SAFE MODE
UPDATE CUSTOMER SET PINCODE = 123456;	-- WITHOUT SAFE MODE IT CANNOT BE CHANGED

UPDATE CUSTOMER SET PINCODE = PINCODE + 1;

-- DELETE THE ROWS
DELETE FROM CUSTOMER WHERE ID = 126;

-- DELETE ENTIRE TABLE
DELETE FROM CUSTOMER;			-- WARN ABOUT SAFE  MODE


CREATE TABLE IF NOT EXISTS ORDER_DETAILS(
	ORDER_ID INTEGER PRIMARY KEY,
    DELIVEY_DATE DATETIME,
    CUST_ID INT,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(ID)
    );
 
 INSERT INTO ORDER_DETAILS 
	(ORDER_ID, DELIVEY_DATE, CUST_ID) VALUES 
		(5,'2023-01-31 17:25:40',125);

DELETE FROM ORDER_DETAILS WHERE ORDER_ID = 5;			-- 1 ST DELETE FROM ORDER_DETAILS

DELETE FROM CUSTOMER WHERE ID = 125;				-- THEN  DELETE IT

SELECT * FROM ORDER_DETAILS;


