CREATE DATABASE CUSTOMER;

USE CUSTOMER;

CREATE TABLE CUSTOMER(
	ID INTEGER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(25),
    ADDRESS VARCHAR(225),
    GENDER CHAR(1),
    CITY VARCHAR(225),
    PINCODE INTEGER(6)
    );


SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER VALUES (
	131,'Pabitra Panigrahi', 'Badapokhari', 'M', 'SORO', 756047);

CREATE TABLE IF NOT EXISTS ORDER_DETAILS(
	ORDER_ID INTEGER PRIMARY KEY,
    DELIVEY_DATE DATETIME,
    CUST_ID INT,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE		-- HELPS TO STORE MULTIPLE ITEM AND DELETE ALSO
    );
 
CREATE TABLE IF NOT EXISTS ORDER_DETAILS(
	ORDER_ID INTEGER PRIMARY KEY,
    DELIVEY_DATE DATETIME,
    CUST_ID INT,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(ID) ON DELETE SET NULL		
    -- HELPS TO STORE MULTIPLE ITEM AND KEEP ORDER DETAILS AS ID IS NULL
    );

 INSERT INTO ORDER_DETAILS 
	(ORDER_ID, DELIVEY_DATE, CUST_ID) VALUES 
		(5,'2023-01-31 17:25:40',131);

 INSERT INTO ORDER_DETAILS 
	(ORDER_ID, DELIVEY_DATE, CUST_ID) VALUES 
		(6,'2023-01-21 17:25:40',131);
        
SELECT * FROM ORDER_DETAILS;

DELETE FROM CUSTOMER WHERE ID=131;